### PR TITLE
dev branch fix, Resolved #185. TEST BEFORE MERGING.

### LINKED ISSUE #185: Fix hardcoded advisor and student ids
In the cart / advisement system there are a lot of hard coded references to the student and advisor ids.

### PR DESCRIPTION
**Pull request by Alcamech**
I tested myself and everything was all good but I want a second pair of eyes on it please. @tbhall @tmoon8730

### CODE REVIEW

**Comment by tbhall** [comment]
Only will log into tbhall account and then gives an error for bad request in current and previous classes

**Comment by Alcamech** [comment]
@tbhall I was able to see current and previous classes. I`ll check again.

**Comment by Alcamech** [comment]
@tbhall I added _id to the req.params for update and delete, this should fix that issue. I think you forget to change the other params in addition to the getById.

**Comment by tmoon8730** [comment]
Tested and it appears to be working @Alcamech @tbhall

**Pull request merged**
